### ISSUE TITLE
Support for .flac files

### ISSUE THREAD

**Issue by JohnKacz** [djdembeck/m4b-merge#48]
First, thanks so much for this and Bragibooks. It been great to finally find a tool that makes using m4b-tool easy and the manual process of confirming the correct ASIN is my preferred process.

I noticed in `find_extension` flac (and other audio formats like aac, ogg, and alac) are not listed. https://github.com/djdembeck/m4b-merge/blob/38f1dfa8481cfb16cd2b34bb77c991a4af43c9db/src/m4b_merge/helpers.py#L10

I know these are likely less common but m4b-tool/ffmpeg support them and I was wondering if there was a technical reason m4b-merge doesn't? If it's not a technical limitation, is there anything beyond just adding them to the `EXTENSIONS` array that would be required to add support?

**Comment by djdembeck** [comment]
It's fairly arbitrary. The main things to consider:
- Does the users' FFMPEG installation support other extensions?
- Tests need to be written for each file extension.

The way the code is written now could also do with some refactoring to be extension/name agnostic, since most of the functions now specifically reference mp3, m4a, etc.

**Comment by djdembeck** [comment]
This is now possible as of https://github.com/djdembeck/m4b-merge/pull/51

Note: I have not officially tested this on different kind of files beyond flac. This now enables processing unknown extensions (so long as it's the first listed file)
