### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by szethh** [djdembeck/m4b-merge#50]
Hi!
I'm currently working on an audiobook manager and your tool seems really cool! However, I've noticed it revolves around CLI usage, are there plans for an API that can be called from other Python scripts?

**Comment by djdembeck** [comment]
https://github.com/laxamentumtech/audnexus

**Comment by MateoPeri** [comment]
Ah, my bad, I meant a python API for the actual handling of the audio files (merging and tagging). For now I'm rolling my own with a python wrapper for FFmpeg. I don't want to use sandreas' m4b-tool because my program will be run in docker, and I'd rather not rely on other containers for it to work.

Audnexus does seem really nice to fetch book metadata though, I'll give it a try when I get to that stage.

**Comment by djdembeck** [comment]
I certainly don't have the expertise to reinvent the wheel of directly editing audio files. While I would like to move to a pure ffmpeg implementation in the future, we would likely still rely on `mp4v2` to handle mutating the file metadata.
